databases:
  - name: newspaper_backend
    ipAllowList: []
    databaseName: newspaper_backend
    user: newspaper_backend

services:
  - type: web
    name: newspaper_backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newspaper_backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    - type: redis
      name: redis
      ipAllowList: []
      plan: free
      maxmemoryPolicy: noeviction
